services:
  - type: web
    name: furia-chatbot
    runtime: python
    repo: https://github.com/Vitu07/furia-chatbot-backend
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: PYTHONUNBUFFERED
        sync: false
      - key: PYTHON_VERSION
        sync: false
      - key: PANDASCORE_API_TOKEN
        sync: false
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: rasa run --enable-api --port 5005 --cors "*" --debug
    autoDeploy: false
version: "1"
